name: mesa-chica/architecture-ui

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.MESA_SHADCN_ACCESS_TOKEN }}" > ~/.npmrc
      - run: npm install
      - run: npm publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MESA_SHADCN_ACCESS_TOKEN }}

  test-install:
    runs-on: ubuntu-latest
    needs: publish-gpr
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Create test project
        run: mkdir test-project

      - name: Initialize test project
        run: cd test-project && npm init -y

      - name: Configure npm for GitHub Packages in test project
        run: |
          echo "@mesa-chica:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.MESA_SHADCN_ACCESS_TOKEN }}" >> ~/.npmrc

      - name: Install published package
        run: cd test-project && npm install @mesa-chica/architecture-ui
